### ISSUE TITLE
Implementation of Custom Knot Strategy is Broken

### ISSUE THREAD

**Issue by EboniWilliams** [uf3/uf3#11]
"Custom" is an option for knot strategy. However, its implementation is currently broken. That is, it will result in an error when used. The problem seems to be that it has "pass" on the get_spacer function so we get the following error:
UnboundLocalError: local variable 'spacing_function' referenced before assignment

**Comment by sxie22** [comment]
I apologize for the confusion. I stopped working on the "custom" knot spacing option, intended to allow for arbitrary functions, due to time constraints and have removed the option (for now). 

The current way to use knots with arbitrary spacing is to construct the knots_map dictionary with custom knot arrays and then passing them to BSplineBasis on initialization. In this case, you do not have to specify r_min_map, r_max_map, and resolution_map. They will be inferred from the provided knots_map.
